### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cbyrne** [Zerite/CraftLib#6]
**Describe the bug**
Not on maven central

**To Reproduce**
1. type lunar maven craftlib in discord
2. not there
3 ????
4. no profit

**Expected behavior**
it should be there

**Additional context**
please fix

**Comment by ChachyDev** [comment]
I agree.

**Comment by KodingDev** [comment]
Hello Conor Byrne,

The CraftLib project is currently waiting for approval on Maven Central.
Marking this issue as irrelevant.

Locked.
